# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'carrierwave-azure', github: 'tsara27/carrierwave-azure'
gem 'colorize'
gem 'ruby-progressbar'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
# gem 'cancancan', '~> 1.10'
gem 'rack', git: 'git://github.com/rack/rack.git'

group :development, :test do
  gem 'bullet'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'rubocop', '~> 0.79.0'
  gem 'simplecov', require: false
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

